#!/bin/bash
ROOT=/home//Documents/CPEN411
benchdirname="sim-cpen411-$1"
echo "$benchdirname"
#tell the system where to find your benchmark folders
benchdir=$ROOT/$benchdirname

if [ $benchdirname = "sim-cpen411-a2" ]; then
benchname="sim-scalar-cpen411"
else
benchname="sim-safe"
fi

cd $benchdir
make
cd ..
declare -a bench
bench[0]="fpppp"
bench[1]="gcc"
bench[2]="go"
bench[3]="vpr"
for name in ${bench[@]}; do

cd ./$name
#add "#!/bin/bash" at the beginning of each of your "readme" file in benchmark folders
bash readme $benchdir $benchname
echo "done the analysis for $name"
cd ..

done
